# Generated by Django 3.0.3 on 2020-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
