# Generated by Django 3.0.3 on 2020-04-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='category',
            field=models.CharField(default=34, max_length=200),
            preserve_default=False,
        ),
    ]
