# Generated by Django 3.0.3 on 2020-06-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0003_about_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('Title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
