# Generated by Django 3.0.3 on 2020-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0004_slideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('FuelType', models.CharField(max_length=50)),
                ('NoSeats', models.IntegerField()),
                ('Powersteering', models.BooleanField(default=False)),
                ('AC', models.BooleanField(default=False)),
                ('BrakeAssist', models.BooleanField(default=False)),
                ('Airbags', models.BooleanField(default=False)),
                ('CDPlayer', models.BooleanField(default=True)),
                ('LeatherSeats', models.BooleanField(default=True)),
                ('CrashSensor', models.BooleanField(default=True)),
                ('Cost_per_day', models.IntegerField()),
            ],
        ),
    ]
